services:
  plin-database:
    image: postgres
    container_name: plin-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=plin_clients
      - POSTGRES_USER=plin
      - POSTGRES_PASSWORD=123456
    networks:
      - development

  application:
    build: .
    container_name: application
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://plin-database:5432/plin_clients
      - DB_USER=plin
      - DB_PASSWORD=123456
      - SELENIUM_GRID=http://selenium-browser:4444
    depends_on:
      - plin-database
      - selenium-browser
    networks:
      - development

  selenium-browser:
    image: selenium/standalone-chrome
    container_name: selenium-browser
    ports:
      - "4442-4444:4442-4444"
    networks:
      - development

networks:
  development:
    driver: bridge